### ISSUE TITLE
Rendered md misses bullet points

### ISSUE THREAD

**Issue by bilderbuchi** [MarcoPolo/lt-markdown#2]
Hi!
When rendering markdown files, I'm missing bullet points in the rendered output (I've seen someone else also has this problem in the discussion group).
I don't know how to debug this, so please advise how I can help tracking this down.

**Comment by MarcoPolo** [comment]
This is probably something to do with we inherit CSS styling from LT. If we can create a rule that restores the  bullet points, we could just add it to the css and we'd be golden. To debug open dev-inspector (by typing dev-inspector in the LT's command pane) and inspect the ul/li elements and play around with their styles. 

I'll take a look at this too, thanks!

**Comment by MarcoPolo** [comment]
Yup it was some styling being overwritten, fixed in the latest verision (0.0.3)

**Comment by bilderbuchi** [comment]
thanks, confirmed working!
