### ISSUE TITLE
Feature: put filename into preview tab name

### ISSUE THREAD

**Issue by bilderbuchi** [MarcoPolo/lt-markdown#3]
Currently, the markdown render tab is just named `markdown`. This gets ambiguous the more render tabs you open.
It would be great if the filename of the rendered file would be incorporated into the render tab name. E.g. `<filename-without-extension>-render`, or something more abbreviated to save space, `-rd`, `-view`,...

**Comment by MarcoPolo** [comment]
That's good! It should be pretty easy to do! If you'd like to take a stab at it go ahead :) if not I'll probably get some time this weekend to add it!

**Comment by MarcoPolo** [comment]
Had some spare time today, and it's up on the latest version as "filename - Live"

**Comment by bilderbuchi** [comment]
thanks, confirmed working!
